name: status_saver
description: A clean, privacy-first WhatsApp Status Saver (images & videos) — offline, ad-free.
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/splash/

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  permission_handler: ^12.0.1
  path_provider: ^2.1.2
  video_player: ^2.8.2
  image_gallery_saver: ^2.0.3
  gallery_saver: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_native_splash: ^2.3.7
  workmanager: ^0.9.0+3
  provider: ^6.0.5
  share_plus:
  intl:

dev_dependencies:
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0